{ :user  {
          :dependencies [
[kioo "0.4.2"] 
[hipo "0.5.2"]


                         [org.clojure/clojure "1.9.0-alpha17"]
                         [org.clojure/clojurescript "1.9.854"]
                         [rewrite-cljs "0.4.3"]
                         [hiccups "0.3.0"]
                         [com.cemerick/piggieback "0.2.1"]
                         [semantic-csv "0.1.0"]
                         [org.clojure/core.async "0.2.385"]
                         [com.jsyn/jsyn "16.7.8"]
                         [aysylu/loom "0.6.0"]
                         [com.cognitect/transit-cljs "0.8.239"]
                         [org.clojure/java.classpath "0.2.3"]
                         [com.cognitect/transit-clj "0.8.293"]
                         [com.itextpdf/itextpdf "5.5.10"]
                         [edu.stanford.nlp/stanford-corenlp "3.6.0"]
                         [reagent "0.6.0-rc"]
                         [org.apache.commons/commons-compress "1.5"]
                         [overtone "0.10.1"]                 ;                         [org.apache.commons/commons-vfs "2 2.1"]
                         [com.google.code.gson/gson "2.8.0"]
                         [com.google.jimfs/jimfs "1.0"]
                         [org.imgscalr/imgscalr-lib "4.2"]
   
;                         [net.sourceforge.tess4j/tess4j "3.2.1"]
   
                         [net.bytebuddy/byte-buddy "1.5.3"]
                         [com.twelvemonkeys.imageio/imageio-core "3.3"]
                         [org.apache.shiro/shiro-core "1.3.2"]
                         [jline/jline "2.12"]
                         [org.apache.commons/commons-lang3 "3.5"]
                         [commons-io/commons-io "2.5"]
                         [clansi "1.0.0"]
                         [rewrite-clj "0.6.0"]
                         [lein-ancient "0.6.10"]
                         [org.clojure/core.typed "0.3.23"]
                         [org.clojure/core.logic "0.8.10"]
                         [com.google.jimfs/jimfs "1.1"]
                         [devcards "0.2.1-7"]
                         [binaryage/dirac "0.6.4"]
                         [binaryage/devtools "0.8.1"]
                         [cljsjs/d3 "4.2.0-0"]
                         [hickory "0.6.0"]
                         [hiccup "1.0.5"]
                         [org.clojure/algo.generic "0.1.2"]
                         [org.clojure/core.match "0.3.0-alpha4"]
                         [org.clojure/core.cache "0.6.5"]
                         [org.clojure/core.memoize "0.5.8"]
                         [instaparse "1.4.3"]
                         [com.google.guava/guava "19.0"]
                         [com.ibm.icu/icu4j "57.1"]
                         [korma "0.4.3"]
                         [funcool/cats "2.0.0"]
                         [quil "2.4.0"]
                         [automat "0.2.0"]
                         [frak "0.1.6"]
                         [clojureverbalexpressions "0.2.1"]
                         [funcool/cuerdas "2.0.0"]
                         [cljsjs/semantic-ui "2.2.2-0"]
                         [io.aviso/pretty "0.1.30"]
                         [spyscope "0.1.5"]
                         [net.cgrand/seqexp "0.6.0"]
                         [cljsjs/chance "0.7.3-0"]
                         [funcool/promesa "1.8.1"]
                         [org.clojure/math.combinatorics "0.1.3"]
                         [org.clojure/test.check "0.9.0"]
                         [org.clojure/tools.analyzer "0.6.9"]
                         [org.clojure/tools.cli "0.3.5"]
                         [org.clojure/tools.macro "0.1.2"]
                         [org.clojure/tools.namespace "0.2.11"]
                         [org.clojure/data.generators "0.1.2"]
                         [ru.lanwen.verbalregex/java-verbal-expressions "1.4"]
                         [org.clojure/data.csv "0.1.3"]
                         [org.clojure/data.json"0.2.6"]
                         [org.apache.commons/commons-math3 "3.6.1"]
                         [ re-frame "0.8.0"]]


          :plugins [
;                    [nightlight/lein-nightlight "1.6.1"]                    ;                    [venantius/ultra "0.5.0"]
 ;                   [lein-marginalia "0.9.0"]
  ;                  [lein-exec "0.3.6"]
   ;                 [lein-datomic "0.2.0"]
    ;                [lein-cljsbuild "1.1.3"]
     ;               [lein-fregec "3.24-7.100"]
                    [lein-figwheel "0.5.4-7" :exclusions [org.clojure/core.cache]]]}
                                        ;                    [figwheel-sidecar "0.5.4-6"] :exclusions [org.clojure/core.cache]]
                                        ; figwheel-sidecar break the initial classpath
 :datomic {:install-location "/Users/eklavya/.m2/repository/datomic/datomic-pro-0.9.5394"}}

:repl {
       :plugins [[cider/cider-nrepl "0.14.0"]
                 [refactor-nrepl "2.3.1"]]

       :dependencies [[alembic "0.3.2"]
                      [org.clojure/tools.nrepl "0.2.12"]]}

